
###################################################
# this(CMakeTestAutoGeneration.cmake) is automatically generated by 'auto_ctest_impl.py'. 
# The behavior of modifying this file is undefined.
###################################################
message(STATUS "load ctests automatic generated success")

add_test(NAME "cd_${CMAKE_BINARY_DIR}/src_&&_${CMAKE_BINARY_DIR}/src/cuda_test_fft" COMMAND bash -c "PYTHONPATH=${CMAKE_BINARY_DIR}/src cd ${CMAKE_BINARY_DIR}/src && ${CMAKE_BINARY_DIR}/src/cuda_test_fft")
set_tests_properties("cd_${CMAKE_BINARY_DIR}/src_&&_${CMAKE_BINARY_DIR}/src/cuda_test_fft" PROPERTIES LABELS "golden;")
    
add_test(NAME "cd_${CMAKE_BINARY_DIR}/src_&&_${CMAKE_BINARY_DIR}/src/cuda_device_info" COMMAND bash -c "PYTHONPATH=${CMAKE_BINARY_DIR}/src cd ${CMAKE_BINARY_DIR}/src && ${CMAKE_BINARY_DIR}/src/cuda_device_info")
set_tests_properties("cd_${CMAKE_BINARY_DIR}/src_&&_${CMAKE_BINARY_DIR}/src/cuda_device_info" PROPERTIES LABELS "golden;")
    
add_test(NAME "cd_${CMAKE_BINARY_DIR}/src_&&_${CMAKE_BINARY_DIR}/src/cuda_test_basic_vt" COMMAND bash -c "PYTHONPATH=${CMAKE_BINARY_DIR}/src cd ${CMAKE_BINARY_DIR}/src && ${CMAKE_BINARY_DIR}/src/cuda_test_basic_vt")
set_tests_properties("cd_${CMAKE_BINARY_DIR}/src_&&_${CMAKE_BINARY_DIR}/src/cuda_test_basic_vt" PROPERTIES LABELS "golden;")
    